export const dummyData = {
  status: "ok",
  total_hits: 10000,
  page: 1,
  total_pages: 200,
  page_size: 50,
  articles: [
    {
      title: "GOP uses state capitol protests to redefine ‘insurrection'",
      author: "Associated Press",
      published_date: "2023-04-28 11:07:19",
      published_date_precision: "timezone unknown",
      link: "https://www.fox28spokane.com/gop-uses-state-capitol-protests-to-redefine-insurrection/",
      clean_url: "fox28spokane.com",
      excerpt:
        "Silenced by her Republican colleagues, Montana state Rep. Zooey Zephyr looked up from the House floor to supporters in the gallery shouting 'Let her speak!' and thrust her microphone into the air —…",
      summary:
        "Silenced by her Republican colleagues, Montana state \nRep. Zooey Zephyr\n looked up from the House floor to supporters in the gallery shouting 'Let her speak!' and thrust her microphone into the air — amplifying the sentiment the Democratic transgender lawmaker was forbidden from expressing.\nIt was a brief moment of defiance and chaos. While seven people were arrested for trespassing, the \nboisterous demonstration\n was free of violence or damage. Yet later that day, a group of Republican lawmakers described it in darker tones, saying Zephyr's actions were responsible for 'encouraging an insurrection.",
      rights: "fox28spokane.com",
      rank: 72502,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Associated Press",
      media:
        "https://www.fox28spokane.com/wp-content/uploads/2016/02/Featured-Image-Fallback-National-News-28.jpg",
      is_opinion: false,
      twitter_account: "@Fox28_Spokane",
      _score: null,
      _id: "b96cc1849cf8debdd5be92fde6de823d",
    },
    {
      title:
        "Bipartisan congressional meeting celebrates Israel on its 75th anniversary",
      author: "",
      published_date: "2023-04-28 11:07:00",
      published_date_precision: "timezone unknown",
      link: "https://www.israelnationalnews.com/news/370671",
      clean_url: "israelnationalnews.com",
      excerpt:
        "All 26 Republican governors join in commitment to Israel and officially recognize Jewish American Heritage Month.",
      summary:
        "Ben Cardin at the Jewish American Heritage Month Congressional Breakfast\nDillon Meyer\nOver a dozen Democrat and Republican Senators and Congressmen came together to celebrate the 75th anniversary of the State of Israel's establishment, reaffirm a commitment to fight Antisemitism, and recognize Jewish American Heritage Month which will take place in May. The historic meeting was the first 'Jewish American Heritage Month Congressional Breakfast: Protecting & Fostering Jewish Life And Combating Contemporary Antisemitism in the United States' organized by the Combat Antisemitism Movement (CAM).",
      rights: "israelnationalnews.com",
      rank: 4617,
      topic: "news",
      country: "IL",
      language: "en",
      authors: "",
      media:
        "https://www.inn.co.il/static/pictures/1200x930/1117291.jpg?autocrop=1",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "b91ce25ea731ac1651a4ccfc2c4589ae",
    },
    {
      title: "BoJ's New Chief Keeps Rate Unchanged; Announces Policy Review",
      author: "Renju Jaya",
      published_date: "2023-04-28 11:07:00",
      published_date_precision: "timezone unknown",
      link: "https://www.rttnews.com/3359663/boj-s-new-chief-keeps-rate-unchanged-announces-policy-review.aspx",
      clean_url: "rttnews.com",
      excerpt:
        "The Bank of Japan maintained its ultra loose monetary policy in the first rate-setting meeting chaired by Governor Kazuo Ueda and announced a broad review of the current stance.",
      summary:
        "The Bank of Japan maintained its ultra loose monetary policy in the first rate-setting meeting chaired by Governor Kazuo Ueda and announced a broad review of the current stance.\n\nThe Policy Board unanimously decided to maintain a negative interest rate of -0.1 percent on current accounts that financial institutions maintain at the central bank.\n\nThe BoJ also unanimously decided to keep its yield curve control policy unchanged. The bank will continue to purchase a necessary amount of Japanese government bonds without setting an upper limit so that 10-year JGB yields will remain at around zero percent.",
      rights: "rttnews.com",
      rank: 18276,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Renju Jaya",
      media:
        "https://cdn.rttnews.com/articleimages/forextopstory/2023/april/bankofjapan-july30_28apr23-lt.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "a7e39fee1d73d54d369186f6d5033e1c",
    },
    {
      title: "Who is the person behind the handle @Asher_Wolf?",
      author: "The Age",
      published_date: "2023-04-28 11:07:00",
      published_date_precision: "timezone unknown",
      link: "https://headtopics.com/au/who-is-the-person-behind-the-handle-asher-wolf-38512081",
      clean_url: "headtopics.com",
      excerpt:
        "Asher Wolf - the pseudonym used by the digital activist who helped bring the robo-debt scandal to light - describes themself on Twitter as a 'mutant network node herder who devours entropy'.",
      summary:
        "Asher Wolf played a critical role in exposing one of the most shameful failures of Australian public administration. But who are they? Advertisement But in person Wolf is warm and empathic, agonising over whether to return the avo toast, which comes with an egg, even though Wolf specified they were vegan. Eventually, Wolf tentatively raises it, apologising profusely.\nThe waiter is disarmed, assuring Wolf it was the cafe's fault, and returning with a beautifully presented fresh dish, this time topped with enoki mushrooms.",
      rights: "headtopics.com",
      rank: 25702,
      topic: "news",
      country: "US",
      language: "en",
      authors: "The Age",
      media:
        "https://i.headtopics.com/images/2023/4/28/theage/who-is-the-person-behind-the-handle-asher-wolf-who-is-the-person-behind-the-handle-asher-wolf-1651770034459652097.webp",
      is_opinion: false,
      twitter_account: "@headtopicscom",
      _score: null,
      _id: "2b925c2adb5791dee33cebb56a9a6494",
    },
    {
      title:
        "Dad to thank York baby unit for care of premature twins with Great North Run effort",
      author: "Ed Horner",
      published_date: "2023-04-28 11:06:34",
      published_date_precision: "timezone unknown",
      link: "https://www.yorkpress.co.uk/news/23487501.joe-set-great-north-run-thank-york-baby-unit-care-twins/",
      clean_url: "yorkpress.co.uk",
      excerpt:
        "A DAD is looking to give thanks to the baby unit at the York trust for the care staff gave to his twins who were born eight weeks early.",
      summary:
        'When Joe and Nikki Logan\'s twin daughters Paige and Phoebe were born in March, eight weeks early, the couple said they "could not have been more grateful" to the special care baby units at both Scarborough and York hospitals for all their help and care.\n\n\n\n Joe wanted to give something back to say thank you for the "amazing care" he and his family received, so he has decided to take on the Great North Run this September to raise funds for York and Scarborough Hospitals Charity.\n\n \n\n\n \nREAD MORE: York schoolgirl strikes gold in top national karate competition\n \n\n\n\n\n Joe plans to run the 13.',
      rights: "yorkpress.co.uk",
      rank: 18307,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "Ed Horner",
      media:
        "https://www.yorkpress.co.uk/resources/images/16719917/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "5993f0d8eb396600f891836093fe68f4",
    },
    {
      title:
        "City Board of Public Works & Safety Approves Plan to Address Flooding Issues at Garro & Plum Streets",
      author: "Posted Kathy Bottorff In",
      published_date: "2023-04-28 11:06:00",
      published_date_precision: "timezone unknown",
      link: "https://www.am1050.com/2023/04/28/city-board-of-public-works-safety-approves-plan-to-address-flooding-issues-at-garro-plum-streets/",
      clean_url: "am1050.com",
      excerpt:
        "A plan to fix the flooding issues that have impacted the Marshall County Neighborhood Center was proposed by Plymouth Utility Superintendent Donnie Davidson during Monday evening's Board of Public…",
      summary:
        "A plan to fix the flooding issues that have impacted the Marshall County Neighborhood Center was proposed by Plymouth Utility Superintendent Donnie Davidson during Monday evening's Board of Public Works and Safety meeting. \n \nDavidson presented a flood control solution that would be constructed at the corner of Garro and Plum Streets. The property is the former Eagles Lodge and is across the street from the Marshall County Neighborhood Center. Davidson said, 'Historically that area has received a lot of flooding.",
      rights: "am1050.com",
      rank: 600650,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Posted Kathy Bottorff In",
      media:
        "https://www.am1050.com/wp-content/uploads/2021/08/Plymouth-Flash-Flood-08.jpg",
      is_opinion: false,
      twitter_account: "@WTCAam1050",
      _score: null,
      _id: "4928624455ac7b2862ef5b2a86c6d174",
    },
    {
      title:
        "Non-thermal Pasteurization Market Key Players, Growth Rate, Size, Share, Value and Forecasts to 2028",
      author: "",
      published_date: "2023-04-28 11:05:53",
      published_date_precision: "timezone unknown",
      link: "https://www.openpr.com/news/3034437/non-thermal-pasteurization-market-key-players-growth-rate",
      clean_url: "openpr.com",
      excerpt:
        "The non thermal pasteurization market is projected to reach USD 5 7 billion by 2028 from USD 2 3 billion by 2023 at a CAGR of 20 0 during the forecast period in terms of value Non thermal…",
      summary:
        "Press release\n \n \n \nNon-thermal Pasteurization Market\nThe non-thermal pasteurization market is projected to reach USD 5.7 billion by 2028 from USD 2.3 billion by 2023, at a CAGR of 20.0% during the forecast period in terms of value. Non-thermal pasteurization products are gaining attention, and consumers are more inclined toward adding more processed and nutritive food. The factors responsible for the growth of the Non-thermal pasteurization industry are the increase in health concerns, evolving protein source preferences, and a thriving food-processing sector that is introducing a wide variety of processed food & beverage products.",
      rights: "openpr.com",
      rank: 9387,
      topic: "business",
      country: "DE",
      language: "en",
      authors: "",
      media: "https://cdn.openpr.com/W/4/W428186785_g.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "2e1989f4c3674386b9985a7e64ced5a0",
    },
    {
      title: "What to know about tick, Lyme season following a mild winter",
      author: "Associated Press",
      published_date: "2023-04-28 11:05:47",
      published_date_precision: "timezone unknown",
      link: "https://www.fox28spokane.com/what-to-know-about-tick-lyme-season-following-a-mild-winter/",
      clean_url: "fox28spokane.com",
      excerpt:
        "PORTLAND, Maine (AP) — After a mild winter in the U.S., scientists are watching to see if there will be an uptick in ticks this year. More ticks this spring could mean a wider spread of Lyme disease…",
      summary:
        "PORTLAND, Maine (AP) — After a mild winter in the U.S., scientists are watching to see if there will be an uptick in ticks this year. More ticks this spring could mean a wider spread of Lyme disease and other infections. Deer ticks, which spread Lyme, are a day-to-day fact of life in the warm months in New England and the Midwest. In Connecticut, a state disease expert says they are already seeing more ticks than usual this month. It varies by region, but tick season generally stretches from April to October and Lyme disease cases peak in the summer.",
      rights: "fox28spokane.com",
      rank: 72502,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Associated Press",
      media:
        "https://www.fox28spokane.com/wp-content/uploads/2016/02/Featured-Image-Fallback-National-News-28.jpg",
      is_opinion: false,
      twitter_account: "@Fox28_Spokane",
      _score: null,
      _id: "884d704a234e735622e946222c2e7503",
    },
    {
      title: "Is this the sexiest audio ever?",
      author: "Hauraki",
      published_date: "2023-04-28 11:05:12",
      published_date_precision: "timezone unknown",
      link: "https://www.hauraki.co.nz/shows/the-matt-jerry-show/podcasts/is-this-the-sexiest-audio-ever-podcast-intro-april-28/",
      clean_url: "hauraki.co.nz",
      excerpt: "Nice Beeeeaver!!!",
      summary: "",
      rights: "hauraki.co.nz",
      rank: 588907,
      topic: "news",
      country: "NZ",
      language: "en",
      authors: "Hauraki",
      media:
        "https://www.hauraki.co.nz/media/1m1ietc3/09389_m_hau_matt-jerry_podcastrollout_880x495_dulux_safe.jpeg?rmode=crop&rnd=132778555317200000&height=395&width=635&quality=95&scale=both",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "9e994eab4f06171f56c403594f876a06",
    },
    {
      title: "Pentair (NYSE:PNR) Releases Q2 2023 Earnings Guidance",
      author: "Jeff Wilder",
      published_date: "2023-04-28 11:04:41",
      published_date_precision: "timezone unknown",
      link: "https://www.dailypolitical.com/2023/04/27/pentair-nysepnr-releases-q2-2023-earnings-guidance.html",
      clean_url: "dailypolitical.com",
      excerpt:
        "Pentair (NYSE:PNR – Get Rating) updated its second quarter 2023 earnings guidance on Thursday. The company provided earnings per share guidance of $0.94-$0.96 for the period, compared to the consensus…",
      summary:
        "Pentair (\nNYSE:PNR\n – \nGet Rating\n) updated its second quarter 2023 earnings guidance on Thursday. The company provided earnings per share guidance of $0.94-$0.96 for the period, compared to the consensus earnings per share estimate of $0.95. The company issued revenue guidance of $1.05 billion-$1.05 billion, compared to the consensus revenue estimate of $1.06 billion. Pentair also updated its FY 2023 guidance to $3.60-$3.70 EPS.\n\n\nAnalysts Set New Price Targets\n\n\nSeveral analysts have weighed in on the stock.",
      rights: "dailypolitical.com",
      rank: 793836,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Jeff Wilder",
      media:
        "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/pentair.jpg&w=240&h=240&zc=2",
      is_opinion: false,
      twitter_account: "@MarketBeatCom",
      _score: null,
      _id: "fe1ced4ee1ff6b9aaa21f8220a5e6f23",
    },
    {
      title: "WEX (NYSE:WEX) Issues FY 2023 Earnings Guidance",
      author: "Latisha Jones",
      published_date: "2023-04-28 11:04:41",
      published_date_precision: "timezone unknown",
      link: "https://www.dailypolitical.com/2023/04/27/wex-nysewex-issues-fy-2023-earnings-guidance.html",
      clean_url: "dailypolitical.com",
      excerpt:
        "WEX (NYSE:WEX – Get Rating) updated its FY 2023 earnings guidance on Thursday. The company provided EPS guidance of $13.85-$14.25 for the period, compared to the consensus EPS estimate of $13.82. The…",
      summary:
        "WEX (\nNYSE:WEX\n – \nGet Rating\n) updated its FY 2023 earnings guidance on Thursday. The company provided EPS guidance of $13.85-$14.25 for the period, compared to the consensus EPS estimate of $13.82. The company issued revenue guidance of $2.43 billion-$2.47 billion, compared to the consensus revenue estimate of $2.47 billion. WEX also updated its FY23 guidance to $13.85-14.25 EPS.\n\n\nAnalyst Upgrades and Downgrades\n\n\nSeveral brokerages have issued reports on WEX. Morgan Stanley upped their target price on WEX from $157.",
      rights: "dailypolitical.com",
      rank: 793836,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Latisha Jones",
      media:
        "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/wex-inc-logo.png?v=20221110144311&w=240&h=240&zc=2",
      is_opinion: false,
      twitter_account: "@MarketBeatCom",
      _score: null,
      _id: "7669a8882a0b61dd0be06bf355e1e684",
    },
    {
      title:
        "Sony Assures Investors Marvel's Spider-Man 2 Is Launching This Financial Year",
      author: "Michael Harradence",
      published_date: "2023-04-28 11:04:36",
      published_date_precision: "timezone unknown",
      link: "https://www.psu.com/news/sony-assures-investors-marvels-spider-man-2-is-launching-this-financial-year/",
      clean_url: "psu.com",
      excerpt:
        "Sony assures its investors that Marvel's Spider-Man 2 will drop this financial year.",
      summary:
        "Speaking during its latest financial results, \nSony Interactive Entertainment\n has assured its investors that the highly anticipated \nMarvel's Spider-Man 2\n will launch during the current financial year.\nThe \nInsomniac Games-developed sequel was previously confirmed for a Fall 2023 release\n, and while no date has been announced yet, it seems that a delay is unlikely at this point. Furthermore, Sony hasn't exactly been forthcoming about any other major PlayStation exclusives this year, so Spider-Man 2 is the big hitter for the back half of 2023.",
      rights: "psu.com",
      rank: 12748,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Michael Harradence",
      media:
        "https://www.psu.com/wp/wp-content/uploads/2023/04/MarvelsSpiderMan2-1-1.jpeg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "37929178ea515ef7a3bf36bc7509019e",
    },
    {
      title: "Album Review: Freya Ridings, Blood Orange",
      author: "Molly Cantwell",
      published_date: "2023-04-28 11:04:34",
      published_date_precision: "timezone unknown",
      link: "https://www.hotpress.com/opinion/album-review-freya-ridings-blood-orange-22965350",
      clean_url: "hotpress.com",
      excerpt: "British pop sensation is back in the game.",
      summary:
        "Album Review: Freya Ridings, \nBlood Orange\n \n \n \n \n \n \n \n \n\n\n \n \n Freya Ridings for 'Blood Orange'\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n Molly Cantwell \n \n \n \n \nBritish pop sensation is back in the game.\n \n \nIt's been four years since the release of \nFreya Ridings'\n breakthrough, self-titled debut, which yielded the \nLove Island\n-boosted megahit ‘Lost Without You'.\n\n\nNow, Freya is back with \nBlood Orange\n – and while the four-year break has yielded fresh, exciting tracks such as ‘Dancing In A Hurricane', ‘Happier Alone', and ‘Bitter', you sense that there is a story behind the album that hasn't been fully told.",
      rights: "hotpress.com",
      rank: 35782,
      topic: "news",
      country: "IE",
      language: "en",
      authors: "Molly Cantwell",
      media:
        "https://img.resized.co/hotpress/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL21lZGlhLmhvdHByZXNzLmNvbVxcXC91cGxvYWRzXFxcLzIwMjNcXFwvMDRcXFwvMTgxMDUyNDlcXFwvRnJleWFSaWRpbmdzLUJsb29kT3JhbmdlLWUxNjgxODEyMzgwNTY1LnBuZ1wiLFwid2lkdGhcIjo2NDcsXCJoZWlnaHRcIjozNDAsXCJkZWZhdWx0XCI6XCJodHRwczpcXFwvXFxcL3d3dy5ob3RwcmVzcy5jb21cXFwvaVxcXC9uby1pbWFnZS5wbmc_dj04XCIsXCJvcHRpb25zXCI6W119IiwiaGFzaCI6IjYwMDkyNDViZTk2NjVmNzRlNDllODNkMjA5MDNjN2U2MzA5YTM2NjIifQ==/freyaridings-bloodorange-e1681812380565.png",
      is_opinion: true,
      twitter_account: null,
      _score: null,
      _id: "223bbbcbe40091a56b7777b725963dd9",
    },
    {
      title:
        "Global Green Ammonia Manufacturing Market Size Is Expected To Grow At An Exceptional Pace During The Forecast Period",
      author: "Xcellent Insights",
      published_date: "2023-04-28 11:03:55",
      published_date_precision: "timezone unknown",
      link: "https://www.openpr.com/news/3034433/global-green-ammonia-manufacturing-market-size-is-expected",
      clean_url: "openpr.com",
      excerpt:
        "Xcellent Insights has recently added a novel report on Global Green Ammonia Manufacturing Market Size Share Growth Analysis By Type Application and Region to its database that offers a comprehensive…",
      summary:
        "Global Green Ammonia Manufacturing Market Size Is Expected To Grow At An Exceptional Pace During The Forecast Period\n\nGreen Ammonia Manufacturing Industry, Green Ammonia Manufacturing Industry Forecast, Green Ammonia Manufacturing market\n\nhttps://www.xcellentinsights.com/enquiry/sample/119280\n\nhttps://www.xcellentinsights.com/checkout/119280\n\nhttps://www.xcellentinsights.com/enquiry/buying/119280\n\nhttps://www.xcellentinsights.com/reports/green-ammonia-manufacturing-market-119280\n\nhttps://www.marketwatch.",
      rights: "openpr.com",
      rank: 9387,
      topic: "news",
      country: "DE",
      language: "en",
      authors: "Xcellent Insights",
      media: "https://cdn.openpr.com/W/4/W428798675_g.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "4ca8f66364ac1a356ad393984130df77",
    },
    {
      title:
        "Port Equipment Market Estimated to Grow at a CAGR of 4.93% was Valued at USD 7.51 Billion in 2021",
      author: "",
      published_date: "2023-04-28 11:03:51",
      published_date_precision: "timezone unknown",
      link: "https://www.openpr.com/news/3034432/port-equipment-market-estimated-to-grow-at-a-cagr-of-4-93-was",
      clean_url: "openpr.com",
      excerpt:
        "Port Equipment Market Report Scope and Research Methodology The report provides an in depth analysis of the global port equipment market including market size drivers restraints and regional insights…",
      summary:
        "Port Equipment Market Estimated to Grow at a CAGR of 4.93% was Valued at USD 7.51 Billion in 2021\n\nPort Equipment Market\n\nhttps://www.maximizemarketresearch.com/market-report/global-port-equipment-market/39567/\n\nhttps://www.maximizemarketresearch.com/request-sample/39567\n\nhttps://www.maximizemarketresearch.com/request-sample/39567\n\nhttps://www.maximizemarketresearch.com/inquiry-before-buying/39567\n\nhttps://www.maximizemarketresearch.com/market-report/global-port-equipment-market/39567/\n\nhttps://www.",
      rights: "openpr.com",
      rank: 9387,
      topic: "news",
      country: "DE",
      language: "en",
      authors: "",
      media: "https://cdn.openpr.com/W/4/W428533042_g.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "548069ab48c58edb4b3781ee3a262532",
    },
    {
      title: "Biometric Access Control Software Market Size in 2023 To 2029",
      author: "",
      published_date: "2023-04-28 11:03:50",
      published_date_precision: "timezone unknown",
      link: "https://www.openpr.com/news/3034431/biometric-access-control-software-market-size-in-2023-to-2029",
      clean_url: "openpr.com",
      excerpt:
        "For clients seeking to make informed investment decisions in emerging markets increase their market share or introduce new products the market report for Biometric Access Control Software is an…",
      summary:
        "Biometric Access Control Software Market Size in 2023 To 2029 | Microsoft, Oracle, Johnson Controls, Honeywell, BioEnable, Kisi, Kintronics, BioConnect and Mantra Softech\n\nhttps://www.reportsnreports.com/contacts/requestsample.aspx?name=7040908\n\nhttps://www.reportsnreports.com/contacts/inquirybeforebuy.aspx?name=7040908\n\nFor clients seeking to make informed investment decisions in emerging markets, increase their market share, or introduce new products, the market report for Biometric Access Control Software is an essential resource.",
      rights: "openpr.com",
      rank: 9387,
      topic: "news",
      country: "DE",
      language: "en",
      authors: "",
      media: null,
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "8b8d67fd5c0223dac671c6c7e76413b0",
    },
    {
      title:
        "Domestic abuse survivor crowned as one of the nation's Coronation Champions",
      author: "Rebecca Mcgrath",
      published_date: "2023-04-28 11:03:50",
      published_date_precision: "timezone unknown",
      link: "https://www.wirralglobe.co.uk/news/23487486.domestic-abuse-survivor-crowned-coronation-champion/",
      clean_url: "wirralglobe.co.uk",
      excerpt:
        "A WIRRAL woman has been chosen as one of the nation's Coronation Champions for her volunteer work.",
      summary:
        "Paula Staunton is one of 500 outstanding volunteers to be chosen by Their Majesties The King and The Queen Consort as part of the official coronation celebrations with the Royal Voluntary Service.\n\n\n\n Paula founded and volunteers with Earth Moves, a grassroots community initiative based in Wallasey that uses horticulture and culture to tackle social issues. \n\n\n\n Paula has been recognised for her contribution in the local community and crowned Coronation Champion after she impressed judges with how she uses her lived experience as a domestic abuse survivor by using gardening to heal from her trauma.",
      rights: "wirralglobe.co.uk",
      rank: 91912,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "Rebecca McGrath",
      media:
        "https://www.wirralglobe.co.uk/resources/images/16719962/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "b7e2c0b09836abf1a3a21530a47cead5",
    },
    {
      title: "Album Review: Jessie Ware, That! Feels Good!",
      author: "Kate Brayden",
      published_date: "2023-04-28 11:03:43",
      published_date_precision: "timezone unknown",
      link: "https://www.hotpress.com/opinion/album-review-jessie-ware-that-feels-good-22965364",
      clean_url: "hotpress.com",
      excerpt: "Euphoric dance queen reemerges with slick, brassy disco-pop.",
      summary:
        "Album Review: Jessie Ware, \nThat! Feels Good!\n \n \n \n \n \n \n \n \n\n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n Kate Brayden \n \n \n \n \nEuphoric dance queen reemerges with slick, brassy disco-pop. \n \n \nThe years after the release of \nJessie Ware\n's deservedly lauded fourth studio album \nWhat's Your Pleasure?\n, the English singer-songwriter thankfully hasn't left the dancefloor quite just yet. Further channelling ‘70s disco to the extreme, the full-bodied 10 tracks are brimming with the 38-year-old's jubilant vocals and thrilling brass sections.",
      rights: "hotpress.com",
      rank: 35782,
      topic: "news",
      country: "IE",
      language: "en",
      authors: "Kate Brayden",
      media:
        "https://img.resized.co/hotpress/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL21lZGlhLmhvdHByZXNzLmNvbVxcXC91cGxvYWRzXFxcLzIwMjNcXFwvMDRcXFwvMjcxMjI1MDFcXFwvSmVzc2llV2FyZS1UaGF0X0ZlZWxzR29vZC1lMTY4MjU5NDczMTU3OS5qcGdcIixcIndpZHRoXCI6NjQ3LFwiaGVpZ2h0XCI6MzQwLFwiZGVmYXVsdFwiOlwiaHR0cHM6XFxcL1xcXC93d3cuaG90cHJlc3MuY29tXFxcL2lcXFwvbm8taW1hZ2UucG5nP3Y9OFwiLFwib3B0aW9uc1wiOltdfSIsImhhc2giOiIyZTY2YzFmY2ExY2NjN2NiMzY4ZjcwZmRmYzA0OWIxM2YxYjZjYWI5In0=/jessieware-that-feelsgood-e1682594731579.jpg",
      is_opinion: true,
      twitter_account: null,
      _score: null,
      _id: "3228cecdd9ea5accdbc9fc0e3153dff3",
    },
    {
      title: "AP Trending SummaryBrief at 12:03 a.m. EDT",
      author: "",
      published_date: "2023-04-28 11:03:42",
      published_date_precision: "timezone unknown",
      link: "https://www.fox28spokane.com/ap-trending-summarybrief-at-1203-a-m-edt/",
      clean_url: "fox28spokane.com",
      excerpt:
        "Zoonomia: Genetic research reveals all we share with animals Scientists from around the world are comparing the genetic blueprints of an array of animals to gain new insights into our own species.…",
      summary:
        "Zoonomia: Genetic research reveals all we share with animals\nScientists from around the world are comparing the genetic blueprints of an array of animals to gain new insights into our own species. It's called the Zoonomia Project. It's the subject of 11 papers published Thursday in the journal Science. One of the most striking revelations is that certain passages in the instructions for life have persisted across evolutionary time. Researchers from around the world were able to figure this out by sequencing and comparing genomes of 240 species of mammals.",
      rights: "fox28spokane.com",
      rank: 72502,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://www.fox28spokane.com/wp-content/uploads/2016/02/Featured-Image-Fallback-National-News-28.jpg",
      is_opinion: false,
      twitter_account: "@Fox28_Spokane",
      _score: null,
      _id: "e6e3ad834e1cf2e46e77057d38271658",
    },
    {
      title: "Terminal Blocks Market to Grow at a CAGR of 5.1% by 2028",
      author: "The Insight",
      published_date: "2023-04-28 11:03:37",
      published_date_precision: "timezone unknown",
      link: "https://www.openpr.com/news/3034430/terminal-blocks-market-to-grow-at-a-cagr-of-5-1-by-2028-impact",
      clean_url: "openpr.com",
      excerpt:
        "According to our latest market study on Terminal Blocks Market Forecast to 2028 Global Analysis by Type Function Type Connection Technologies Industry and Device Type the market is expected to grow…",
      summary:
        'Terminal Blocks Market to Grow at a CAGR of 5.1% by 2028 - Impact of COVID-19 Pandemic and Global Analysis by The Insight Partners\n\nTerminal Blocks Market\n\nhttps://www.theinsightpartners.com/sample/TIPRE00012057/?utm_source=OpenPR&utm_medium=10706\n\nhttps://www.theinsightpartners.com/buy/TIPRE00012057/?utm_source=OpenPR&utm_medium=10706\n\nAccording to our latest market study on "Terminal Blocks Market Forecast to 2028 -Global Analysis - by Type, Function Type, Connection Technologies, Industry, and Device Type," the market is expected to grow from US$ 4,559.',
      rights: "openpr.com",
      rank: 9387,
      topic: "news",
      country: "DE",
      language: "en",
      authors: "The Insight,The Insight  Partners",
      media: "https://cdn.openpr.com/W/4/W428793385_g.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "4badfa2b1210e2931e74e6e69a3d2004",
    },
    {
      title:
        "Jurgen Klopp not willing to say Liverpool are back to their best just yet",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:28",
      published_date_precision: "timezone unknown",
      link: "https://www.hillingdontimes.co.uk/sport/national/23487484.jurgen-klopp-not-willing-say-liverpool-back-best-just-yet/",
      clean_url: "hillingdontimes.co.uk",
      excerpt: "The Reds have strung together some impressive results.",
      summary:
        "The midweek victory over West Ham made it three wins in succession, extended their unbeaten run to five matches, and maintained their outside chance of sneaking into the top four.\n\n\nOn Sunday at home to Tottenham, Liverpool have a chance to win a fourth league game in a row for only the second time this season – that came in November and December and was separated by the World Cup – but Klopp said it would be wrong to assume everything had now clicked back into place.\n \n\n\n.\n@IbrahimaKonate_\n is available for \n#LIVTOT\n this weekend 🙌\n\n\n— Liverpool FC (@LFC) \nApril 28, 2023\n\n\n\n\n'It is, for me too early to speak about consistency,' he said.",
      rights: "hillingdontimes.co.uk",
      rank: 392308,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.hillingdontimes.co.uk/resources/images/16719982/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "4a0fc265717b5287b35a2f9662249366",
    },
    {
      title:
        "Jurgen Klopp not willing to say Liverpool are back to their best just yet",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:28",
      published_date_precision: "timezone unknown",
      link: "https://www.penarthtimes.co.uk/sport/national/23487484.jurgen-klopp-not-willing-say-liverpool-back-best-just-yet/",
      clean_url: "penarthtimes.co.uk",
      excerpt: "The Reds have strung together some impressive results.",
      summary:
        "The midweek victory over West Ham made it three wins in succession, extended their unbeaten run to five matches, and maintained their outside chance of sneaking into the top four.\n\n\nOn Sunday at home to Tottenham, Liverpool have a chance to win a fourth league game in a row for only the second time this season – that came in November and December and was separated by the World Cup – but Klopp said it would be wrong to assume everything had now clicked back into place.\n \n\n\n.\n@IbrahimaKonate_\n is available for \n#LIVTOT\n this weekend 🙌\n\n\n— Liverpool FC (@LFC) \nApril 28, 2023\n\n\n\n\n'It is, for me too early to speak about consistency,' he said.",
      rights: "penarthtimes.co.uk",
      rank: 406853,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.penarthtimes.co.uk/resources/images/16719982/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "4146329d4f9e1f9d8cb4051ae434b537",
    },
    {
      title:
        "Jurgen Klopp not willing to say Liverpool are back to their best just yet",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:28",
      published_date_precision: "timezone unknown",
      link: "https://www.knutsfordguardian.co.uk/sport/national/23487484.jurgen-klopp-not-willing-say-liverpool-back-best-just-yet/",
      clean_url: "knutsfordguardian.co.uk",
      excerpt: "The Reds have strung together some impressive results.",
      summary:
        "The midweek victory over West Ham made it three wins in succession, extended their unbeaten run to five matches, and maintained their outside chance of sneaking into the top four.\n\n\nOn Sunday at home to Tottenham, Liverpool have a chance to win a fourth league game in a row for only the second time this season – that came in November and December and was separated by the World Cup – but Klopp said it would be wrong to assume everything had now clicked back into place.\n \n\n\n.\n@IbrahimaKonate_\n is available for \n#LIVTOT\n this weekend 🙌\n\n\n— Liverpool FC (@LFC) \nApril 28, 2023\n\n\n\n\n'It is, for me too early to speak about consistency,' he said.",
      rights: "knutsfordguardian.co.uk",
      rank: 244556,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.knutsfordguardian.co.uk/resources/images/16719982/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "4f504360c2ecee2f9f89d16ce9a94552",
    },
    {
      title:
        "Jurgen Klopp not willing to say Liverpool are back to their best just yet",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:28",
      published_date_precision: "timezone unknown",
      link: "https://www.milfordmercury.co.uk/sport/national/23487484.jurgen-klopp-not-willing-say-liverpool-back-best-just-yet/",
      clean_url: "milfordmercury.co.uk",
      excerpt: "The Reds have strung together some impressive results.",
      summary:
        "The midweek victory over West Ham made it three wins in succession, extended their unbeaten run to five matches, and maintained their outside chance of sneaking into the top four.\n\n\nOn Sunday at home to Tottenham, Liverpool have a chance to win a fourth league game in a row for only the second time this season – that came in November and December and was separated by the World Cup – but Klopp said it would be wrong to assume everything had now clicked back into place.\n \n\n\n.\n@IbrahimaKonate_\n is available for \n#LIVTOT\n this weekend 🙌\n\n\n— Liverpool FC (@LFC) \nApril 28, 2023\n\n\n\n\n'It is, for me too early to speak about consistency,' he said.",
      rights: "milfordmercury.co.uk",
      rank: 491987,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.milfordmercury.co.uk/resources/images/16719982/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "a27c4dee088a2ddeaaabbc8a4c76edfa",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.northwalespioneer.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "northwalespioneer.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "northwalespioneer.co.uk",
      rank: 288945,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.northwalespioneer.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "fb3a20a8c69b91403c47799198ddd142",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.peeblesshirenews.com/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "peeblesshirenews.com",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "peeblesshirenews.com",
      rank: 304792,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.peeblesshirenews.com/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "cc95e50e538fc101ff22a8600da92a68",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.leaderlive.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "leaderlive.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "leaderlive.co.uk",
      rank: 77272,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.leaderlive.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "d2d2a2ba735c0f0a3ac4a26716a01fd4",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.ledburyreporter.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "ledburyreporter.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "ledburyreporter.co.uk",
      rank: 478153,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.ledburyreporter.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "9a2063a4568c323aefd70178d1d8066e",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.northwaleschronicle.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "northwaleschronicle.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "northwaleschronicle.co.uk",
      rank: 175134,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.northwaleschronicle.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "66c7bc21a6201186883299a84048acc5",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.penarthtimes.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "penarthtimes.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "penarthtimes.co.uk",
      rank: 406853,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.penarthtimes.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "a84536cee7efe318db5b2b09876d8d5d",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.huntspost.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "huntspost.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "huntspost.co.uk",
      rank: 156244,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.huntspost.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "e1b9885c370a81ae2da1d5ab409a3634",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.nwemail.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "nwemail.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "nwemail.co.uk",
      rank: 41788,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.nwemail.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "47d1eca0f6f1cb96fba9bed377e82459",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "full",
      link: "https://www.ludlowadvertiser.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "ludlowadvertiser.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "ludlowadvertiser.co.uk",
      rank: 690618,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.ludlowadvertiser.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "5d59c2d373e684a360e77fc075c02972",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.knutsfordguardian.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "knutsfordguardian.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "knutsfordguardian.co.uk",
      rank: 244556,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.knutsfordguardian.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "526d4fa366c73ac98348ddf9c95b0949",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "timezone unknown",
      link: "https://www.hillingdontimes.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "hillingdontimes.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "hillingdontimes.co.uk",
      rank: 392308,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.hillingdontimes.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "94e064725d207c9c84bf3bd73f74300d",
    },
    {
      title:
        "Rob Baxter targets a vintage display as Exeter aim to taste victory in Bordeaux",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:26",
      published_date_precision: "full",
      link: "https://www.milfordmercury.co.uk/sport/national/23487483.rob-baxter-targets-vintage-display-exeter-aim-taste-victory-bordeaux/",
      clean_url: "milfordmercury.co.uk",
      excerpt:
        "The Devon side have a tough task against the reigning European champions on Sunday.",
      summary:
        "But Exeter will arrive at the 42,000-capacity Mahmut Atlantique stadium in Bordeaux on Sunday determined to underline their own rich European pedigree.\n\n\nThe 2020 champions are England's sole survivors, having won five out of six games in Europe this season, including a gripping last-16 success against French champions Montpellier.\n \nExeter players celebrate after winning the Heineken Champions Cup in 2020 (David Davies/PA)\nAnd they have got there despite patchy domestic form that undermined their Gallagher Premiership play-off bid as Chiefs missed out behind confirmed semi-finalists Saracens, Sale, Leicester and Northampton.",
      rights: "milfordmercury.co.uk",
      rank: 491987,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.milfordmercury.co.uk/resources/images/16719981/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "f67df161b382b237f0391557385a0ea8",
    },
    {
      title:
        "Richard Sharp resigns as BBC chair after breaching appointment rules",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:24",
      published_date_precision: "timezone unknown",
      link: "https://www.northwaleschronicle.co.uk/news/national/23487283.richard-sharp-resigns-bbc-chair-breaching-appointment-rules/",
      clean_url: "northwaleschronicle.co.uk",
      excerpt:
        "He was found to have broken the rules by failing to disclose his role in helping Boris Johnson secure a loan guarantee.",
      summary:
        "Adam Heppinstall KC's review found the former Tory donor twice breached the code governing public appointments, risking the perception he was not independent from the then-prime minister.\n\n\nMr Sharp spared forcing Rishi Sunak to decide on his fate by announcing he will stand down from the influential role overseeing the public broadcaster's independence at the end of June.\n \nThe barrister's review published on Friday morning said Mr Sharp risked a perception that he was recommended for the role because he assisted Mr Johnson 'in a private financial matter' ahead of his appointment in 2021.",
      rights: "northwaleschronicle.co.uk",
      rank: 175134,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.northwaleschronicle.co.uk/resources/images/12229501/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "50a5f6a439e54062147208300c70017e",
    },
    {
      title:
        "Richard Sharp resigns as BBC chair after breaching appointment rules",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:24",
      published_date_precision: "timezone unknown",
      link: "https://www.peeblesshirenews.com/news/national/23487283.richard-sharp-resigns-bbc-chair-breaching-appointment-rules/",
      clean_url: "peeblesshirenews.com",
      excerpt:
        "He was found to have broken the rules by failing to disclose his role in helping Boris Johnson secure a loan guarantee.",
      summary:
        "Adam Heppinstall KC's review found the former Tory donor twice breached the code governing public appointments, risking the perception he was not independent from the then-prime minister.\n\n\nMr Sharp spared forcing Rishi Sunak to decide on his fate by announcing he will stand down from the influential role overseeing the public broadcaster's independence at the end of June.\n \nThe barrister's review published on Friday morning said Mr Sharp risked a perception that he was recommended for the role because he assisted Mr Johnson 'in a private financial matter' ahead of his appointment in 2021.",
      rights: "peeblesshirenews.com",
      rank: 304792,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.peeblesshirenews.com/resources/images/12229501/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "59dc933108c57bfda401ee2731e937d7",
    },
    {
      title:
        "Richard Sharp resigns as BBC chair after breaching appointment rules",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:24",
      published_date_precision: "timezone unknown",
      link: "https://www.leaderlive.co.uk/news/national/23487283.richard-sharp-resigns-bbc-chair-breaching-appointment-rules/",
      clean_url: "leaderlive.co.uk",
      excerpt:
        "He was found to have broken the rules by failing to disclose his role in helping Boris Johnson secure a loan guarantee.",
      summary:
        "Adam Heppinstall KC's review found the former Tory donor twice breached the code governing public appointments, risking the perception he was not independent from the then-prime minister.\n\n\nMr Sharp spared forcing Rishi Sunak to decide on his fate by announcing he will stand down from the influential role overseeing the public broadcaster's independence at the end of June.\n \nThe barrister's review published on Friday morning said Mr Sharp risked a perception that he was recommended for the role because he assisted Mr Johnson 'in a private financial matter' ahead of his appointment in 2021.",
      rights: "leaderlive.co.uk",
      rank: 77272,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.leaderlive.co.uk/resources/images/12229501/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "3b77683148bf1b8880929b8e199b749e",
    },
    {
      title:
        "Richard Sharp resigns as BBC chair after breaching appointment rules",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:24",
      published_date_precision: "timezone unknown",
      link: "https://www.irvinetimes.com/news/national/23487283.richard-sharp-resigns-bbc-chair-breaching-appointment-rules/",
      clean_url: "irvinetimes.com",
      excerpt:
        "He was found to have broken the rules by failing to disclose his role in helping Boris Johnson secure a loan guarantee.",
      summary:
        "Adam Heppinstall KC's review found the former Tory donor twice breached the code governing public appointments, risking the perception he was not independent from the then-prime minister.\n\n\nMr Sharp spared forcing Rishi Sunak to decide on his fate by announcing he will stand down from the influential role overseeing the public broadcaster's independence at the end of June.\n \nThe barrister's review published on Friday morning said Mr Sharp risked a perception that he was recommended for the role because he assisted Mr Johnson 'in a private financial matter' ahead of his appointment in 2021.",
      rights: "irvinetimes.com",
      rank: 311885,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.irvinetimes.com/resources/images/12229501/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "fa924e9d02daea16e6b6bb24cca7488f",
    },
    {
      title:
        "Richard Sharp resigns as BBC chair after breaching appointment rules",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:24",
      published_date_precision: "timezone unknown",
      link: "https://www.hertsad.co.uk/news/national/23487283.richard-sharp-resigns-bbc-chair-breaching-appointment-rules/",
      clean_url: "hertsad.co.uk",
      excerpt:
        "He was found to have broken the rules by failing to disclose his role in helping Boris Johnson secure a loan guarantee.",
      summary:
        "Adam Heppinstall KC's review found the former Tory donor twice breached the code governing public appointments, risking the perception he was not independent from the then-prime minister.\n\n\nMr Sharp spared forcing Rishi Sunak to decide on his fate by announcing he will stand down from the influential role overseeing the public broadcaster's independence at the end of June.\n \nThe barrister's review published on Friday morning said Mr Sharp risked a perception that he was recommended for the role because he assisted Mr Johnson 'in a private financial matter' ahead of his appointment in 2021.",
      rights: "hertsad.co.uk",
      rank: 126927,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.hertsad.co.uk/resources/images/12229501/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "396384fc7fccdd76833b8e8819049c8b",
    },
    {
      title:
        "Richard Sharp resigns as BBC chair after breaching appointment rules",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:24",
      published_date_precision: "timezone unknown",
      link: "https://www.islingtongazette.co.uk/news/national/23487283.richard-sharp-resigns-bbc-chair-breaching-appointment-rules/",
      clean_url: "islingtongazette.co.uk",
      excerpt:
        "He was found to have broken the rules by failing to disclose his role in helping Boris Johnson secure a loan guarantee.",
      summary:
        "Adam Heppinstall KC's review found the former Tory donor twice breached the code governing public appointments, risking the perception he was not independent from the then-prime minister.\n\n\nMr Sharp spared forcing Rishi Sunak to decide on his fate by announcing he will stand down from the influential role overseeing the public broadcaster's independence at the end of June.\n \nThe barrister's review published on Friday morning said Mr Sharp risked a perception that he was recommended for the role because he assisted Mr Johnson 'in a private financial matter' ahead of his appointment in 2021.",
      rights: "islingtongazette.co.uk",
      rank: 84343,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.islingtongazette.co.uk/resources/images/12229501/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "87d48480c003f08ae90a44c144fc5314",
    },
    {
      title:
        "Richard Sharp resigns as BBC chair after breaching appointment rules",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:24",
      published_date_precision: "timezone unknown",
      link: "https://www.northwalespioneer.co.uk/news/national/23487283.richard-sharp-resigns-bbc-chair-breaching-appointment-rules/",
      clean_url: "northwalespioneer.co.uk",
      excerpt:
        "He was found to have broken the rules by failing to disclose his role in helping Boris Johnson secure a loan guarantee.",
      summary:
        "Richard Sharp has resigned as BBC chairman after being found to have broken the rules by failing to disclose he played a role in getting Boris Johnson an £800,000 loan guarantee.\n\nAdam Heppinstall KC's review found the former Tory donor twice breached the code governing public appointments, risking the perception he was not independent from the then-prime minister.\n\nMr Sharp spared forcing Rishi Sunak to decide on his fate by announcing he will stand down from the influential role overseeing the public broadcaster's independence at the end of June.",
      rights: "northwalespioneer.co.uk",
      rank: 288945,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.northwalespioneer.co.uk/resources/images/12229501.jpg?type=mds-article-620",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "137e10aa12f82ce68851dbd5d7d9e463",
    },
    {
      title: "Eva Green wins High Court battle over sci-fi film collapse",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:20",
      published_date_precision: "timezone unknown",
      link: "https://www.cravenherald.co.uk/news/national/23487256.eva-green-wins-high-court-battle-sci-fi-film-collapse/",
      clean_url: "cravenherald.co.uk",
      excerpt:
        "Mr Justice Michael Green ruled she is entitled to her million-dollar (£810,000) fee for the film despite its collapse.",
      summary:
        "The 42-year-old sued White Lantern Film after production on A Patriot was shuttered in October 2019, claiming she was entitled to her million-dollar (£810,000) fee for the film, despite its cancellation, under the terms of their agreement.\n\n\nWhite Lantern Film and lender SMC Speciality Finance (SMC) brought a counter-claim against Ms Green, alleging she undermined the independent film's production and renounced the contract.\n \nIn a judgment on Friday, Mr Justice Michael Green found in Ms Green's favour, ruling she was entitled to the fee and dismissing the counter-claim.",
      rights: "cravenherald.co.uk",
      rank: 157930,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.cravenherald.co.uk/resources/images/16405844/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "5f326401b35bec8e34135562f202c915",
    },
    {
      title: "Eva Green wins High Court battle over sci-fi film collapse",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:20",
      published_date_precision: "timezone unknown",
      link: "https://www.hertsad.co.uk/news/national/23487256.eva-green-wins-high-court-battle-sci-fi-film-collapse/",
      clean_url: "hertsad.co.uk",
      excerpt:
        "Mr Justice Michael Green ruled she is entitled to her million-dollar (£810,000) fee for the film despite its collapse.",
      summary:
        "The 42-year-old sued White Lantern Film after production on A Patriot was shuttered in October 2019, claiming she was entitled to her million-dollar (£810,000) fee for the film, despite its cancellation, under the terms of their agreement.\n\n\nWhite Lantern Film and lender SMC Speciality Finance (SMC) brought a counter-claim against Ms Green, alleging she undermined the independent film's production and renounced the contract.\n \nIn a judgment on Friday, Mr Justice Michael Green found in Ms Green's favour, ruling she was entitled to the fee and dismissing the counter-claim.",
      rights: "hertsad.co.uk",
      rank: 126927,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.hertsad.co.uk/resources/images/16405844/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "a4547383139eec3adde29b8fb5efcddf",
    },
    {
      title: "Eva Green wins High Court battle over sci-fi film collapse",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:20",
      published_date_precision: "timezone unknown",
      link: "https://www.gazetteseries.co.uk/news/national/23487256.eva-green-wins-high-court-battle-sci-fi-film-collapse/",
      clean_url: "gazetteseries.co.uk",
      excerpt:
        "Mr Justice Michael Green ruled she is entitled to her million-dollar (£810,000) fee for the film despite its collapse.",
      summary:
        "The 42-year-old sued White Lantern Film after production on A Patriot was shuttered in October 2019, claiming she was entitled to her million-dollar (£810,000) fee for the film, despite its cancellation, under the terms of their agreement.\n\n\nWhite Lantern Film and lender SMC Speciality Finance (SMC) brought a counter-claim against Ms Green, alleging she undermined the independent film's production and renounced the contract.\n \nIn a judgment on Friday, Mr Justice Michael Green found in Ms Green's favour, ruling she was entitled to the fee and dismissing the counter-claim.",
      rights: "gazetteseries.co.uk",
      rank: 148398,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.gazetteseries.co.uk/resources/images/16405844/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "2cba7d1e9cd7c19e9d5b4888f98b8942",
    },
    {
      title: "Eva Green wins High Court battle over sci-fi film collapse",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:20",
      published_date_precision: "timezone unknown",
      link: "https://www.northwaleschronicle.co.uk/news/national/23487256.eva-green-wins-high-court-battle-sci-fi-film-collapse/",
      clean_url: "northwaleschronicle.co.uk",
      excerpt:
        "Mr Justice Michael Green ruled she is entitled to her million-dollar (£810,000) fee for the film despite its collapse.",
      summary:
        "The 42-year-old sued White Lantern Film after production on A Patriot was shuttered in October 2019, claiming she was entitled to her million-dollar (£810,000) fee for the film, despite its cancellation, under the terms of their agreement.\n\n\nWhite Lantern Film and lender SMC Speciality Finance (SMC) brought a counter-claim against Ms Green, alleging she undermined the independent film's production and renounced the contract.\n \nIn a judgment on Friday, Mr Justice Michael Green found in Ms Green's favour, ruling she was entitled to the fee and dismissing the counter-claim.",
      rights: "northwaleschronicle.co.uk",
      rank: 175134,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.northwaleschronicle.co.uk/resources/images/16405844/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "f7c42751cbb6160846c9ff138d80908d",
    },
    {
      title: "Eva Green wins High Court battle over sci-fi film collapse",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:20",
      published_date_precision: "timezone unknown",
      link: "https://www.chelmsfordweeklynews.co.uk/news/national/23487256.eva-green-wins-high-court-battle-sci-fi-film-collapse/",
      clean_url: "chelmsfordweeklynews.co.uk",
      excerpt:
        "Mr Justice Michael Green ruled she is entitled to her million-dollar (£810,000) fee for the film despite its collapse.",
      summary:
        "The 42-year-old sued White Lantern Film after production on A Patriot was shuttered in October 2019, claiming she was entitled to her million-dollar (£810,000) fee for the film, despite its cancellation, under the terms of their agreement.\n\n\nWhite Lantern Film and lender SMC Speciality Finance (SMC) brought a counter-claim against Ms Green, alleging she undermined the independent film's production and renounced the contract.\n \nIn a judgment on Friday, Mr Justice Michael Green found in Ms Green's favour, ruling she was entitled to the fee and dismissing the counter-claim.",
      rights: "chelmsfordweeklynews.co.uk",
      rank: 379640,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.chelmsfordweeklynews.co.uk/resources/images/16405844/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "8a3fd4ee3b0311c0e43d991f1e449512",
    },
    {
      title: "Eva Green wins High Court battle over sci-fi film collapse",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:20",
      published_date_precision: "timezone unknown",
      link: "https://www.wandsworthguardian.co.uk/news/national/23487256.eva-green-wins-high-court-battle-sci-fi-film-collapse/",
      clean_url: "wandsworthguardian.co.uk",
      excerpt:
        "Mr Justice Michael Green ruled she is entitled to her million-dollar (£810,000) fee for the film despite its collapse.",
      summary:
        "The 42-year-old sued White Lantern Film after production on A Patriot was shuttered in October 2019, claiming she was entitled to her million-dollar (£810,000) fee for the film, despite its cancellation, under the terms of their agreement.\n\n\nWhite Lantern Film and lender SMC Speciality Finance (SMC) brought a counter-claim against Ms Green, alleging she undermined the independent film's production and renounced the contract.\n \nIn a judgment on Friday, Mr Justice Michael Green found in Ms Green's favour, ruling she was entitled to the fee and dismissing the counter-claim.",
      rights: "wandsworthguardian.co.uk",
      rank: 167797,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.wandsworthguardian.co.uk/resources/images/16405844/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "ddc1225d59893f1ac7c25ad1b7c22fa1",
    },
    {
      title: "Eva Green wins High Court battle over sci-fi film collapse",
      author: "PA News Agency",
      published_date: "2023-04-28 11:03:20",
      published_date_precision: "timezone unknown",
      link: "https://www.irvinetimes.com/news/national/23487256.eva-green-wins-high-court-battle-sci-fi-film-collapse/",
      clean_url: "irvinetimes.com",
      excerpt:
        "Mr Justice Michael Green ruled she is entitled to her million-dollar (£810,000) fee for the film despite its collapse.",
      summary:
        "The 42-year-old sued White Lantern Film after production on A Patriot was shuttered in October 2019, claiming she was entitled to her million-dollar (£810,000) fee for the film, despite its cancellation, under the terms of their agreement.\n\n\nWhite Lantern Film and lender SMC Speciality Finance (SMC) brought a counter-claim against Ms Green, alleging she undermined the independent film's production and renounced the contract.\n \nIn a judgment on Friday, Mr Justice Michael Green found in Ms Green's favour, ruling she was entitled to the fee and dismissing the counter-claim.",
      rights: "irvinetimes.com",
      rank: 311885,
      topic: "news",
      country: "GB",
      language: "en",
      authors: "PA News Agency",
      media:
        "https://www.irvinetimes.com/resources/images/16405844/?type=og-image",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "ffcee5af64ac62fe8243b16d80eec76f",
    },
  ],
  user_input: {
    lang: ["en"],
    not_lang: null,
    countries: null,
    not_countries: null,
    page: 1,
    size: 50,
    sources: null,
    not_sources: [],
    topic: null,
    from: "2023-04-21 11:07:29",
  },
};
